apiVersion: v2
name: cert-manager-webhook-opentelekomcloud
description: ACME DNS01 solver webhook for Open Telekom Cloud DNS

version: 0.2.0
appVersion: "v0.1.5"

maintainers:
  - name: Kyriakos Akriotis
    url: https://github.com/akyriako
