apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cert-manager-webhook-opentelekomcloud.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "cert-manager-webhook-opentelekomcloud.name" . }}
    chart: {{ include "cert-manager-webhook-opentelekomcloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cert-manager-webhook-opentelekomcloud.fullname" . }}:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: {{ include "cert-manager-webhook-opentelekomcloud.name" . }}
    chart: {{ include "cert-manager-webhook-opentelekomcloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "cert-manager-webhook-opentelekomcloud.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-webhook-opentelekomcloud.fullname" . }}:auth-delegator
  labels:
    app: {{ include "cert-manager-webhook-opentelekomcloud.name" . }}
    chart: {{ include "cert-manager-webhook-opentelekomcloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "cert-manager-webhook-opentelekomcloud.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# apiserver gets the secret-reader role to read cluster-wide secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-webhook-opentelekomcloud.fullname" . }}:secret-reader
  labels:
    app: {{ include "cert-manager-webhook-opentelekomcloud.name" . }}
    chart: {{ include "cert-manager-webhook-opentelekomcloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cert-manager-webhook-opentelekomcloud.fullname" . }}:secret-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "cert-manager-webhook-opentelekomcloud.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# Grant webhook permission to get secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-manager-webhook-opentelekomcloud.fullname" . }}:secret-reader
  labels:
    app: {{ include "cert-manager-webhook-opentelekomcloud.name" . }}
    chart: {{ include "cert-manager-webhook-opentelekomcloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - 'get'
      - 'list'
---
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-manager-webhook-opentelekomcloud.fullname" . }}:domain-solver
  labels:
    app: {{ include "cert-manager-webhook-opentelekomcloud.name" . }}
    chart: {{ include "cert-manager-webhook-opentelekomcloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - {{ .Values.groupName }}
    resources:
      - '*'
    verbs:
      - 'create'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-webhook-opentelekomcloud.fullname" . }}:domain-solver
  labels:
    app: {{ include "cert-manager-webhook-opentelekomcloud.name" . }}
    chart: {{ include "cert-manager-webhook-opentelekomcloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cert-manager-webhook-opentelekomcloud.fullname" . }}:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ .Values.certManager.serviceAccountName }}
    namespace: {{ .Values.certManager.namespace }}
